apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: pspd
data:
  AUTHORIZATION_SERVICE_URL: "http://authorization-service:8002"
  ANTIFRAUD_SERVICE_URL: "http://antifraud-service:8001"
  PAYMENT_GATEWAY_PORT: "8000"
  DEFAULT_PROTOCOL: "rest"
  ANTIFRAUD_REST_URL: "http://antifraud-service:8001"
  AUTHORIZER_REST_URL: "http://authorization-service:8002"
  ANTIFRAUD_GRPC_ADDR: "antifraud-grpc-headless:50051"
  AUTHORIZER_GRPC_ADDR: "authorization-grpc-headless:50052"
  GRPC_TIMEOUT: "5.0"
  REST_TIMEOUT: "5.0"
  LOG_LEVEL: "INFO"
  GRPC_CHANNEL_POOL_SIZE: "8"
  WEB_CONCURRENCY: "4"
  REDIS_URL: "redis://redis:6379/0"
